Test on try/catch if throw in the try
It's possible to throw in the try
